apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: nginx
  namespace: default
spec:
  rules:
  - host: nginx.marisa.im
    http:
      paths:
      - backend:
          serviceName: nginx-app-1
          servicePort: 80
