apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: whoami
  namespace: default
spec:
  rules:
  - host: sharelist.marisa.im
    http:
      paths:
      - backend:
          serviceName: sharelist
          servicePort: 33001
